test: &default

  # Credentials for REST APIs
  # client_id: EBWKjlELKMYqRNQ6sYvFo64FtaRLRR5BdHEESmha49TM
  # client_secret: EO422dn3gQLgDbuwqTjzrFgFtaRLRR5BdHEESmha49TM

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: danielbc+paypal1_api1.gmail.com
  password: 1381891309
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31AdYNqT0chXyCBMwAG0TG9--VJZxP
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  #sandbox_email_address: danielbc+paypal1@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live